### <div style="text-align: right"> NAME: GATALE ELIJAH </div>
### <div style="text-align: right"> REG NO. : 2023/HD05/20093U </div>
### <div style="text-align: right"> STD NO. : 2300720093 </div>

### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [91]:
lower = 60
upper = 69
for n in range(lower, upper+1):
    print(n)

60
61
62
63
64
65
66
67
68
69


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [3]:
def mean_and_std(num):
    total = 0
    count = 0
    sum_of_squares = 0
    if num == 0:
        break
    total += num
    count += 1
    sum_of_squares += num ** 2
    mean = total / count
    variance = (sum_of_squares / count) - (mean ** 2)
    std_dev = variance ** 0.5
    print(f"Mean: {mean:.2f}")
    print(f"Standard deviation: {std_dev:.2f}")


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [90]:
# YOUR CODE HERE
l = [2, 3, -2, -7, 0, 2, 3]
for item in l:
    if item % 2 == 1:
        print(item)
# raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [92]:
# YOUR CODE HERE
def get_n_primes(N):
    primes = []
    num = 2
    while len(primes) < N:
        for i in range(2, num):
            if (num % i) == 0:
                break
        else:
            primes.append(num)
        num += 1
    return primes

In [93]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [94]:
# YOUR CODE HERE
# raise NotImplementedError()
def get_nth_fibonacci(n):
    if n < 0:
        return ValueError
    if n == 0:
        return 0
    elif n == 1:
        return 1
    elif n == 2:
        return 1
    else:
        return get_nth_fibonacci(n - 1) + get_nth_fibonacci(n - 2)

In [95]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [97]:
# YOUR CODE HERE

def filter_list(lst, predicate):
    return list(filter(predicate, lst))

def is_odd(n):
    if n%2 == 1:
        return True
    
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

In [98]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [99]:
# YOUR CODE HERE
from typing import List

def reduce(l: List, f, init=None):
    if init is None:
        result = l[0]
        for i in range(1, len(l)):
            result = f(result, l[i])
    else:
        result = init
        for i in range(len(l)):
            result = f(result, l[i])
    return result


def add(x: int, y: int) -> int:
    return x + y

def string_len_add(x: int, y: str) -> int:
    return x + len(y)

In [100]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [101]:
def count_odd(lst):
    return reduce(lst, lambda acc, x: acc + (x % 2 == 1), 0)

count_odd([2, -1, 4, 9, 3])

3

In [102]:
def find_max(lst):
    return reduce(lst, lambda acc, x: max(acc, x), lst[0])

find_max([2, -1, 4, 9, 3])

9

In [103]:
def find_longest(lst):
    return reduce(lst, lambda acc, x: acc if len(acc) > len(x) else x, lst[0])

find_longest(['foo', 'bar', '34-bar'])

'34-bar'

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [104]:
from sklearn.metrics.pairwise import euclidean_distances

def pairwise_row_distance(A):
    return (euclidean_distances(A)).tolist()


In [105]:
def is_matrix(D):
    if isinstance(D, list) and all(isinstance(row, list) for row in D):
        return True
    else:
        return False

In [106]:
def transpose(D):
    return [list(x) for x in zip(*D)]

In [107]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [108]:
# YOUR CODE HERE
# raise NotImplementedError()
class A:
    def __init__(self, value) -> None:
        self.value = value
    def print_value(self):
        print(self.value)


a_instance = A('Some Value')
a_instance.print_value()

Some Value


In [109]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [110]:
# YOUR CODE HERE
class B:
    def __init__(self, public_attr, private_attr):
        self.this_is_public = public_attr
        self.__this_is_private = private_attr

In [111]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [112]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [113]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [114]:
# YOUR CODE HERE
class Animal:
    def __init__(self, age=0, number_of_legs=0):
        self.age = age
        self.number_of_legs = number_of_legs

    def make_sound(self):
        pass

class Cat(Animal):
    def __init__(self, age=0, number_of_legs=4, fur='black'):
        super().__init__(age, number_of_legs)
        self.fur = fur if isinstance(fur, (list, tuple)) else [fur]

    def make_sound(self):
        print('Meow!')

class Dog(Animal):
    def __init__(self, age=0, number_of_legs=4, fur_color='brown'):
        super().__init__(age, number_of_legs)
        self.fur = fur if isinstance(fur, (list, tuple)) else [fur]

    def make_sound(self):
        print('Woof!')

class Eagle(Animal):
    def make_sound(self):
        print('Screech!')

In [115]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

Could not initialize an animal: __init__() got multiple values for argument 'age'


#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [117]:
# %pip install numpy
import numpy as np


def standardize(X):
    return (X - np.mean(X, axis=0)) / np.std(X, axis=0)

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-0.70710678, -0.70710678],
       [ 1.41421356,  1.41421356],
       [-0.70710678, -0.70710678]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [118]:
def normalize(X):
    return (X - np.min(X)) / (np.max(X) - np.min(X))

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0.55555556, 0.66666667, 0.77777778],
       [0.88888889, 1.        , 0.        ]])

In [119]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)

AssertionError: 